baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Craft Coding Challenge'
primary: true
siteGroup: 0d89c679-f6f5-42ae-8341-4bea917c6af7 # Craft Coding Challenge
sortOrder: 1
